create extension if not exists pgcrypto;

create table if not exists public.app_users (
  mid bigint generated by default as identity primary key,
  uid uuid references auth.users(id) on delete set null,
  status text not null default 'active' check (status in ('active', 'withdrawn')),
  created_at timestamptz not null default now(),
  withdrawn_at timestamptz
);

create table if not exists public.auth_identities (
  mid bigint not null references public.app_users(mid) on delete cascade,
  uid uuid references auth.users(id) on delete set null,
  provider text not null,
  provider_user_id text,
  provider_user_id_hash text,
  email text,
  email_hash text,
  provider_name text,
  provider_avatar_url text,
  raw_metadata jsonb not null default '{}'::jsonb,
  linked_at timestamptz not null default now(),
  unlinked_at timestamptz,
  primary key (mid, provider)
);

create index if not exists auth_identities_mid_idx on public.auth_identities(mid);
create index if not exists auth_identities_provider_user_id_idx on public.auth_identities(provider, provider_user_id);
create index if not exists auth_identities_email_hash_idx on public.auth_identities(email_hash);
create unique index if not exists auth_identities_active_provider_hash_key
on public.auth_identities(provider, provider_user_id_hash)
where provider_user_id_hash is not null and unlinked_at is null;

create table if not exists public.admin_users (
  uid uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_users
    where uid = auth.uid()
  );
$$;

create or replace function public.current_mid()
returns bigint
language sql
security definer
set search_path = public
as $$
  select mid
  from public.auth_identities
  where uid = auth.uid()
    and unlinked_at is null
  order by linked_at desc
  limit 1;
$$;

create table if not exists public.profiles (
  mid bigint primary key references public.app_users(mid) on delete cascade,
  nickname text not null default 'zeta',
  username text unique,
  avatar_url text,
  bio text,
  birthdate date,
  gender text,
  onboarding_completed boolean not null default false,
  account_status text not null default 'active' check (account_status in ('active', 'withdrawn')),
  withdrawn_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  mid bigint primary key references public.app_users(mid) on delete cascade,
  dialogue_mode text not null default 'unlimited' check (dialogue_mode in ('safe', 'unlimited')),
  marketing_opt_in boolean not null default false,
  chat_background_enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.notification_preferences (
  mid bigint not null references public.app_users(mid) on delete cascade,
  category text not null,
  key text not null,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (mid, category, key)
);

create table if not exists public.user_blocks (
  id uuid primary key default gen_random_uuid(),
  mid bigint not null references public.app_users(mid) on delete cascade,
  target_type text not null check (target_type in ('creator', 'plot', 'hashtag')),
  target_id text not null,
  target_label text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (mid, target_type, target_id)
);

create table if not exists public.follows (
  follower_mid bigint not null references public.app_users(mid) on delete cascade,
  following_mid bigint not null references public.app_users(mid) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_mid, following_mid),
  check (follower_mid <> following_mid)
);

create index if not exists follows_follower_idx on public.follows(follower_mid);
create index if not exists follows_following_idx on public.follows(following_mid);

create table if not exists public.creators (
  id text primary key,
  mid bigint references public.app_users(mid) on delete set null,
  display_name text not null,
  handle text,
  avatar_url text,
  bio text,
  status text not null default 'active' check (status in ('active', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plots (
  id text primary key,
  creator_id text references public.creators(id) on delete set null,
  title text not null,
  subtitle text,
  description text,
  tags text[] not null default '{}',
  thumbnail_url text,
  chat_count bigint not null default 0,
  rank_score numeric not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'hidden')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists plots_public_order_idx
on public.plots(status, rank_score desc, published_at desc);

create table if not exists public.piece_products (
  id bigint generated by default as identity primary key,
  pieces integer not null check (pieces > 0),
  price_krw integer not null check (price_krw >= 0),
  bonus_pieces integer not null default 0 check (bonus_pieces >= 0),
  label text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  mid bigint not null references public.app_users(mid) on delete cascade,
  plan_code text not null,
  status text not null default 'active' check (status in ('active', 'expired', 'canceled')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists memberships_mid_status_idx on public.memberships(mid, status, ends_at desc);

create table if not exists public.auto_charge_settings (
  mid bigint primary key references public.app_users(mid) on delete cascade,
  enabled boolean not null default false,
  threshold_pieces integer not null default 0,
  charge_product_id bigint references public.piece_products(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_mid bigint references public.app_users(mid) on delete set null,
  target_type text not null check (target_type in ('creator', 'plot', 'hashtag', 'user')),
  target_id text not null,
  target_label text,
  reason text not null,
  detail text,
  status text not null default 'open' check (status in ('open', 'reviewing', 'closed')),
  created_at timestamptz not null default now()
);

create index if not exists reports_target_idx on public.reports(target_type, target_id, created_at desc);

create table if not exists public.wallets (
  mid bigint primary key references public.app_users(mid) on delete cascade,
  piece_balance integer not null default 0 check (piece_balance >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.piece_ledger (
  id uuid primary key default gen_random_uuid(),
  mid bigint not null references public.app_users(mid) on delete cascade,
  amount integer not null,
  reason text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create index if not exists piece_ledger_mid_created_idx on public.piece_ledger(mid, created_at desc);

create table if not exists public.policy_documents (
  slug text primary key,
  title text not null,
  body_markdown text not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.account_withdrawals (
  id bigint generated by default as identity primary key,
  mid bigint references public.app_users(mid) on delete set null,
  provider text,
  provider_user_id_hash text,
  email_hash text,
  reason text not null,
  detail text not null,
  records_retention_policy text not null default 'preserve_all',
  rejoin_block_until timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now()
);

create index if not exists account_withdrawals_provider_hash_idx
on public.account_withdrawals(provider, provider_user_id_hash, rejoin_block_until);

create index if not exists account_withdrawals_email_hash_idx
on public.account_withdrawals(email_hash, rejoin_block_until);

create or replace function public.touch_core_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_core_updated_at();

drop trigger if exists user_settings_touch_updated_at on public.user_settings;
create trigger user_settings_touch_updated_at
before update on public.user_settings
for each row execute function public.touch_core_updated_at();

drop trigger if exists notification_preferences_touch_updated_at on public.notification_preferences;
create trigger notification_preferences_touch_updated_at
before update on public.notification_preferences
for each row execute function public.touch_core_updated_at();

drop trigger if exists creators_touch_updated_at on public.creators;
create trigger creators_touch_updated_at
before update on public.creators
for each row execute function public.touch_core_updated_at();

drop trigger if exists plots_touch_updated_at on public.plots;
create trigger plots_touch_updated_at
before update on public.plots
for each row execute function public.touch_core_updated_at();

drop trigger if exists piece_products_touch_updated_at on public.piece_products;
create trigger piece_products_touch_updated_at
before update on public.piece_products
for each row execute function public.touch_core_updated_at();

drop trigger if exists memberships_touch_updated_at on public.memberships;
create trigger memberships_touch_updated_at
before update on public.memberships
for each row execute function public.touch_core_updated_at();

drop trigger if exists auto_charge_settings_touch_updated_at on public.auto_charge_settings;
create trigger auto_charge_settings_touch_updated_at
before update on public.auto_charge_settings
for each row execute function public.touch_core_updated_at();

drop trigger if exists wallets_touch_updated_at on public.wallets;
create trigger wallets_touch_updated_at
before update on public.wallets
for each row execute function public.touch_core_updated_at();

drop trigger if exists policy_documents_touch_updated_at on public.policy_documents;
create trigger policy_documents_touch_updated_at
before update on public.policy_documents
for each row execute function public.touch_core_updated_at();

alter table public.admin_users enable row level security;
alter table public.app_users enable row level security;
alter table public.auth_identities enable row level security;
alter table public.profiles enable row level security;
alter table public.user_settings enable row level security;
alter table public.notification_preferences enable row level security;
alter table public.user_blocks enable row level security;
alter table public.follows enable row level security;
alter table public.creators enable row level security;
alter table public.plots enable row level security;
alter table public.piece_products enable row level security;
alter table public.memberships enable row level security;
alter table public.auto_charge_settings enable row level security;
alter table public.reports enable row level security;
alter table public.wallets enable row level security;
alter table public.piece_ledger enable row level security;
alter table public.policy_documents enable row level security;
alter table public.account_withdrawals enable row level security;

drop policy if exists "admins can read admin users" on public.admin_users;
create policy "admins can read admin users"
on public.admin_users for select
using (public.is_admin() or uid = auth.uid());

drop policy if exists "users can read own app user" on public.app_users;
create policy "users can read own app user"
on public.app_users for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "users can read own auth identities" on public.auth_identities;
create policy "users can read own auth identities"
on public.auth_identities for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile"
on public.profiles for insert
with check (mid = public.current_mid());

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles for update
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can manage own settings" on public.user_settings;
create policy "users can manage own settings"
on public.user_settings for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can manage own notification preferences" on public.notification_preferences;
create policy "users can manage own notification preferences"
on public.notification_preferences for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can manage own blocks" on public.user_blocks;
create policy "users can manage own blocks"
on public.user_blocks for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can read own follows" on public.follows;
create policy "users can read own follows"
on public.follows for select
using (follower_mid = public.current_mid() or following_mid = public.current_mid() or public.is_admin());

drop policy if exists "public can read active creators" on public.creators;
create policy "public can read active creators"
on public.creators for select
using (status = 'active');

drop policy if exists "admins can manage creators" on public.creators;
create policy "admins can manage creators"
on public.creators for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can read published plots" on public.plots;
create policy "public can read published plots"
on public.plots for select
using (status = 'published');

drop policy if exists "admins can manage plots" on public.plots;
create policy "admins can manage plots"
on public.plots for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can read active piece products" on public.piece_products;
create policy "public can read active piece products"
on public.piece_products for select
using (is_active = true);

drop policy if exists "admins can manage piece products" on public.piece_products;
create policy "admins can manage piece products"
on public.piece_products for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users can read own memberships" on public.memberships;
create policy "users can read own memberships"
on public.memberships for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "users can manage own auto charge settings" on public.auto_charge_settings;
create policy "users can manage own auto charge settings"
on public.auto_charge_settings for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can create reports" on public.reports;
create policy "users can create reports"
on public.reports for insert
with check (reporter_mid = public.current_mid());

drop policy if exists "admins can read reports" on public.reports;
create policy "admins can read reports"
on public.reports for select
using (public.is_admin());

drop policy if exists "users can read own wallet" on public.wallets;
create policy "users can read own wallet"
on public.wallets for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "admins can manage wallets" on public.wallets;
create policy "admins can manage wallets"
on public.wallets for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users can read own ledger" on public.piece_ledger;
create policy "users can read own ledger"
on public.piece_ledger for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "admins can manage ledger" on public.piece_ledger;
create policy "admins can manage ledger"
on public.piece_ledger for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "published policies are public" on public.policy_documents;
create policy "published policies are public"
on public.policy_documents for select
using (status = 'published' and published_at <= now());

drop policy if exists "admins can manage policies" on public.policy_documents;
create policy "admins can manage policies"
on public.policy_documents for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can read account withdrawals" on public.account_withdrawals;
create policy "admins can read account withdrawals"
on public.account_withdrawals for select
using (public.is_admin());
