create table if not exists public.conversation_profiles (
  id bigint generated by default as identity primary key,
  mid bigint not null references public.app_users(mid) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  description text,
  avatar_url text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists conversation_profiles_mid_idx
on public.conversation_profiles(mid, is_default desc, created_at);

create unique index if not exists conversation_profiles_one_default_idx
on public.conversation_profiles(mid)
where is_default = true;

drop trigger if exists conversation_profiles_touch_updated_at on public.conversation_profiles;
create trigger conversation_profiles_touch_updated_at
before update on public.conversation_profiles
for each row execute function public.touch_core_updated_at();

alter table public.conversation_profiles enable row level security;

drop policy if exists "users can manage own conversation profiles" on public.conversation_profiles;
create policy "users can manage own conversation profiles"
on public.conversation_profiles for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

alter table public.profiles
alter column nickname drop default;
