alter table public.user_settings
add column if not exists chat_background_enabled boolean not null default false;

create table if not exists public.follows (
  follower_mid bigint not null references public.app_users(mid) on delete cascade,
  following_mid bigint not null references public.app_users(mid) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_mid, following_mid),
  check (follower_mid <> following_mid)
);

create index if not exists follows_follower_idx on public.follows(follower_mid);
create index if not exists follows_following_idx on public.follows(following_mid);

create table if not exists public.creators (
  id text primary key,
  mid bigint references public.app_users(mid) on delete set null,
  display_name text not null,
  handle text,
  avatar_url text,
  bio text,
  status text not null default 'active' check (status in ('active', 'hidden')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plots (
  id text primary key,
  creator_id text references public.creators(id) on delete set null,
  title text not null,
  subtitle text,
  description text,
  tags text[] not null default '{}',
  thumbnail_url text,
  chat_count bigint not null default 0,
  rank_score numeric not null default 0,
  status text not null default 'published' check (status in ('draft', 'published', 'hidden')),
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists plots_public_order_idx
on public.plots(status, rank_score desc, published_at desc);

create table if not exists public.piece_products (
  id bigint generated by default as identity primary key,
  pieces integer not null check (pieces > 0),
  price_krw integer not null check (price_krw >= 0),
  bonus_pieces integer not null default 0 check (bonus_pieces >= 0),
  label text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.memberships (
  id bigint generated by default as identity primary key,
  mid bigint not null references public.app_users(mid) on delete cascade,
  plan_code text not null,
  status text not null default 'active' check (status in ('active', 'expired', 'canceled')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists memberships_mid_status_idx on public.memberships(mid, status, ends_at desc);

create table if not exists public.auto_charge_settings (
  mid bigint primary key references public.app_users(mid) on delete cascade,
  enabled boolean not null default false,
  threshold_pieces integer not null default 0,
  charge_product_id bigint references public.piece_products(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_mid bigint references public.app_users(mid) on delete set null,
  target_type text not null check (target_type in ('creator', 'plot', 'hashtag', 'user')),
  target_id text not null,
  target_label text,
  reason text not null,
  detail text,
  status text not null default 'open' check (status in ('open', 'reviewing', 'closed')),
  created_at timestamptz not null default now()
);

create index if not exists reports_target_idx on public.reports(target_type, target_id, created_at desc);

drop trigger if exists creators_touch_updated_at on public.creators;
create trigger creators_touch_updated_at
before update on public.creators
for each row execute function public.touch_core_updated_at();

drop trigger if exists plots_touch_updated_at on public.plots;
create trigger plots_touch_updated_at
before update on public.plots
for each row execute function public.touch_core_updated_at();

drop trigger if exists piece_products_touch_updated_at on public.piece_products;
create trigger piece_products_touch_updated_at
before update on public.piece_products
for each row execute function public.touch_core_updated_at();

drop trigger if exists memberships_touch_updated_at on public.memberships;
create trigger memberships_touch_updated_at
before update on public.memberships
for each row execute function public.touch_core_updated_at();

drop trigger if exists auto_charge_settings_touch_updated_at on public.auto_charge_settings;
create trigger auto_charge_settings_touch_updated_at
before update on public.auto_charge_settings
for each row execute function public.touch_core_updated_at();

alter table public.follows enable row level security;
alter table public.creators enable row level security;
alter table public.plots enable row level security;
alter table public.piece_products enable row level security;
alter table public.memberships enable row level security;
alter table public.auto_charge_settings enable row level security;
alter table public.reports enable row level security;

drop policy if exists "users can read own follows" on public.follows;
create policy "users can read own follows"
on public.follows for select
using (follower_mid = public.current_mid() or following_mid = public.current_mid() or public.is_admin());

drop policy if exists "public can read active creators" on public.creators;
create policy "public can read active creators"
on public.creators for select
using (status = 'active');

drop policy if exists "admins can manage creators" on public.creators;
create policy "admins can manage creators"
on public.creators for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can read published plots" on public.plots;
create policy "public can read published plots"
on public.plots for select
using (status = 'published');

drop policy if exists "admins can manage plots" on public.plots;
create policy "admins can manage plots"
on public.plots for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "public can read active piece products" on public.piece_products;
create policy "public can read active piece products"
on public.piece_products for select
using (is_active = true);

drop policy if exists "admins can manage piece products" on public.piece_products;
create policy "admins can manage piece products"
on public.piece_products for all
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users can read own memberships" on public.memberships;
create policy "users can read own memberships"
on public.memberships for select
using (mid = public.current_mid() or public.is_admin());

drop policy if exists "users can manage own auto charge settings" on public.auto_charge_settings;
create policy "users can manage own auto charge settings"
on public.auto_charge_settings for all
using (mid = public.current_mid())
with check (mid = public.current_mid());

drop policy if exists "users can create reports" on public.reports;
create policy "users can create reports"
on public.reports for insert
with check (reporter_mid = public.current_mid());

drop policy if exists "admins can read reports" on public.reports;
create policy "admins can read reports"
on public.reports for select
using (public.is_admin());

insert into public.piece_products (pieces, price_krw, sort_order)
values
  (200, 2000, 10),
  (500, 5000, 20),
  (1000, 10000, 30),
  (2000, 20000, 40),
  (3000, 30000, 50),
  (5000, 50000, 60),
  (10000, 100000, 70)
on conflict do nothing;
